### PR TITLE
Fixed UI of landing page

### PR DESCRIPTION
**Pull request by coder12git**
***Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
I have fixed UI of landing page.

* **What is the current behavior?** (You can also link to an open issue here)

Screenshot 2023-08-30 122449

Screenshot 2023-08-30 122506

* **What is the new behavior (if this is a feature change)?**

Screenshot 2023-08-30 122341

Screenshot 2023-08-30 122356

Screenshot 2023-08-30 122430

### CODE REVIEW

**Comment by coder12git** [comment]
@fisherxu please review :)

**Review by anvithks — APPROVED** [review]
LGTM

**Comment by anvithks** [comment]
Reviewed again after merging from upstream master.

/lgtm 
/approve

**Comment by coder12git** [comment]
Any update?

**Review by fisherxu — COMMENTED** [review]
/approve
Thanks for the fixing :)

**Pull request merged**
