### PR TITLE
trans /content/zh/docs/roadmap.md

### PR DESCRIPTION
**Pull request by chuanhaojin**
* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

trans /content/zh/docs/roadmap.md

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

I translate the doc in  `` kubeedge/kubeedge ``, not tranlate this doc `` kubeedge/website/content/zh/docs/roadmap.md``

### CODE REVIEW

**Comment by chuanhaojin** [comment]
I translate the doc in kubeedge/kubeedge, 

not tranlate this doc kubeedge/website/content/zh/docs/roadmap.md,

May I update the English doc - roadmap.md ?

**Comment by kevin-wangzefeng** [comment]
@chuanhaojin Thanks for pointing it out, please update the en doc accordingly :-)

**Comment by chuanhaojin** [comment]
@kevin-wangzefeng It`s done.Thanks for your attention. :)

**Review by kevin-wangzefeng — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
