### PR TITLE
update dependency

### PR DESCRIPTION
**Pull request by Arhell**
* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
@Shelley-BaoYue
@kevin-wangzefeng

**Comment by Arhell** [comment]
cc @fisherxu  there is an opportunity to add me to this repository, I will follow the updates like this PR

**Comment by fisherxu** [comment]
> cc @fisherxu there is an opportunity to add me to this repository, I will follow the updates like this PR

What's meaning of add you to repo?

**Comment by Arhell** [comment]
> > cc @fisherxu there is an opportunity to add me to this repository, I will follow the updates like this PR
> 
> Could you explain what's meaning of add you to repo?

merge access

**Comment by fisherxu** [comment]
In KubeEdge community the code is merged by @kubeedge-bot which is controlled by prow.
The OWNERS file includes all the maintainers who can control the @kubeedge-bot , the reviewer can add lgtm label, the appover can add `approve` label, then the @kubeedge-bot will merge the code.

As description in https://github.com/kubeedge/community/blob/master/community-membership.md#kubeedge-community-membership, comunity developers can apply the related role as needed. ptal @Arhell thanks.

**Comment by Arhell** [comment]
> In KubeEdge community the code is merged by @kubeedge-bot which is controlled by prow. The OWNERS file includes all the maintainers who can control the @kubeedge-bot , the reviewer can add lgtm label, the appover can add `approve` label, then the @kubeedge-bot will merge the code.
> 
> As description in https://github.com/kubeedge/community/blob/master/community-membership.md#kubeedge-community-membership, comunity developers can apply the related role as needed. ptal @Arhell thanks.

Understood thanks

**Comment by Arhell** [comment]
updated to latest version docusaurus and other dependency

**Comment by Shelley-BaoYue** [comment]
Regarding the updates of dependencies, I have some questions as well. I think that if it doesn't affect the usage of the website, we may don't need to track the latest versions in real-time. It is sufficient to periodically update to the current stable versions. As for the frequency of these updates, it can be aligned with the version release cycle, updating every three months. This is just my suggestion.

**Pull request closed without merging**
