### PR TITLE
Accessibility add link name

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/kubeedge/website/issues/211

### CODE REVIEW

**Comment by fisherxu** [comment]
What does this pr will fixed? @Arhell

**Comment by Arhell** [comment]
> What does this pr will fix? @Arhell

An accessible name is a word or phrase coded in a way that assistive technologies can associate it with a specific user interface object. Assistive technologies can then refer to the object by name, not just by type. When a link doesn’t have an accessible name, people who use assistive technologies have no way of knowing its purpose.

Accessibility Insights extension

**Comment by Arhell** [comment]
cc @kevin-wangzefeng

**Review by kevin-wangzefeng — COMMENTED** [review]
This is located in the theme folder of Hugo Academic, I think we should replace in our folder, or update Academic theme version.

**Pull request closed without merging**
