### PR TITLE
update container runtime docs

### PR DESCRIPTION
**Pull request by Shelley-BaoYue**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

docs update

* **What is the current behavior?** (You can also link to an open issue here)

The container runtime docs is outdated, which can cause confusion and difficulties for users. 

#433 

* **What is the new behavior (if this is a feature change)?**

Update this container runtime

https://deploy-preview-474--competent-hypatia-4195b7.netlify.app/docs/setup/prerequisites/runtime 
https://deploy-preview-474--competent-hypatia-4195b7.netlify.app/zh/docs/setup/prerequisites/runtime

### CODE REVIEW

**Comment by Shelley-BaoYue** [comment]
PTAL @fisherxu @WillardHu @ZhengXinwei-F @luomengY @wbc6080

**Comment by ZhengXinwei-F** [comment]
lgtm

**Review by fisherxu — COMMENTED** [review]
/approve
/assign @WillardHu

**Pull request merged**
