### PR TITLE
[Bug] - Fixed Unrendered Escape Characters

### LINKED ISSUE #350: [Bug] - Homepage has escape characters along with content
**Describe the bug**
Homepage has escape characters along with content, please refer the below screenshot for the same

**To Reproduce**
1. Go to 'https://kubeedge.io/'
2. Scroll down to 'Why KubeEdge' section
3. See error

**Expected behavior**
The escape character should be removed or should be hidden while retaining its functionality

**Screenshots**

Screenshot 2023-07-29 at 12 54 24 PM

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Brave, Safari

### PR DESCRIPTION
**Pull request by krishnasvp**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

- Fixes escape characters which were not being rendered

**What is the current behavior?** (You can also link to an open issue here)

- Fixes #350 

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

- No, this PR does not introduce a breaking change

### CODE REVIEW

**Comment by fisherxu** [comment]
cc @Arhell  
PTAL :)

**Review by Arhell — COMMENTED** [review]
/lgtm

**Comment by kevin-wangzefeng** [comment]
/approve
Thanks

**Pull request merged**
