### PR TITLE
Bug: We need to fix some links for local development

### LINKED ISSUE #566: Fix: We need to fix some links for local development
**Describe the bug**

for e.g. during local development when you click "documentation" to takes you to "https://kubeedge.io/docs/" rather than "localhost:3000/docs" . Hence the changes you make will not be reflected on the website.

**Additional context**

### PR DESCRIPTION
**Pull request by 1Shubham7**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
bug fix

* **What is the new behavior (if this is a feature change)?**

during local development when you click "documentation" it takes you to "https://kubeedge.io/docs/" rather than "localhost:3000/docs" . I have fixed that.

Fixes #566 

Works towards solving #533

### CODE REVIEW

**Comment by 1Shubham7** [comment]
@fisherxu @Shelley-BaoYue I would suggest we should call it "latest" rather than "next". what do you say?

**Comment by Shelley-BaoYue** [comment]
> @fisherxu @Shelley-BaoYue I would suggest we should call it "latest" rather than "next". what do you say?

I think "latest" is not appropriate here. "Latest" could be misleading and imply that this is the most recently released version. In reality, what we want to convey is that this is the upcoming version - the one that is currently in development and has not yet been officially released.

**Review by Shelley-BaoYue — COMMENTED** [review]
/lgtm

**Review by fisherxu — COMMENTED** [review]
/approve

**Pull request merged**
