### PR TITLE
New blog for summer-ospp

### PR DESCRIPTION
**Pull request by Catherine-monk**
* **Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

docs update

* **What is the new behavior (if this is a feature change)?**
add a blog for activity of summer-ospp

### CODE REVIEW

**Review by fisherxu — COMMENTED** [review]
We need to create the dir and index for English version, or the blog can't be displayed in web page.
The tile can be translate to English `Summer OSPP 2024 is coming! KubeEdge community has launched registrations`

The content can be `Please refer to the detailed introduction of the Summer OSPP in the Chinese version of the blog.    https://kubeedge.io/zh/blog/summer-ospp`

**Comment by Catherine-monk** [comment]
It has been updated.

**Review by fisherxu — COMMENTED** [review]
/approve
Looks good!

**Review by fisherxu — COMMENTED** [review]
/assign @WillardHu @Shelley-BaoYue @wbc6080 @zhiyingfang2022

**Review by wbc6080 — APPROVED** [review]
/lgtm

**Pull request merged**
