### PR TITLE
Add DaoCloud as A KubeEdge Partner

### PR DESCRIPTION
**Pull request by zhiyingfang2022**
* **Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
docs update

### CODE REVIEW

**Comment by zhiyingfang2022** [comment]
cc @fisherxu @Shelley-BaoYue @WillardHu @JiaweiGithub

**Review by fisherxu — COMMENTED** [review]
/approve
Thanks for the contributions and the best product for the community!

**Review by fisherxu — COMMENTED** [review]
/cc @kubeedge/tsc

**Pull request merged**
