### PR TITLE
Redesign home

### PR DESCRIPTION
**Pull request by dzr201732120115**
* **What kind of change does this PR introduce?**
Redesign home page: 
1.redesign slider and delete useless selection  
2.etc wait for next pr(step by step)

* **What is the new behavior (if this is a feature change)?**
new silder and update the navbar
image
image

* **Does this PR introduce a breaking change?** 
No, all change didn't relate to files in academic .

* **Other information**:
It supports en and zh .I didn't update ko(Korean). 
The first access to the image load is slower，same as orgin, but now only one image is needed.
demo: [https://testke.netlify.app/en/](url)
/assign @kevin-wangzefeng

### CODE REVIEW

**Comment by anvithks** [comment]
@dzr201732120115 Is this how the site is supposed to look ?
I clicked on the [deploy preview](https://deploy-preview-91--kubeedge.netlify.app/en/) and this is what I am seeing.
Let me know if this is expected.
image

**Comment by dzr201732120115** [comment]
> @dzr201732120115 Is this how the site is supposed to look ?
> I clicked on the [deploy preview](https://deploy-preview-91--kubeedge.netlify.app/en/) and this is what I am seeing.
> Let me know if this is expected.
> image
Because it now depends on the cache, there is no need to load or wait after the first load, and the same is true for previous images，this pr's main purpose is to show effects and provide demo addresses，I would optimize it

**Comment by dzr201732120115** [comment]
**This pr is not for merge, but deploy preivew.** 

latest update：[demo](https://testke.netlify.app/en/)

Note：can't update at daytime

**Pull request merged**
