### PR TITLE
Fix: change remote URL

### PR DESCRIPTION
**Pull request by rajatgupta24**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Documentation Update

* **What is the current behavior?** (You can also link to an open issue here)
The remote URL doesn't work 

* **What is the new behavior (if this is a feature change)?**
New URL is working

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
NA

* **Other information**:

### CODE REVIEW

**Review by fisherxu — COMMENTED** [review]
Thanks for the fixing! @rajatgupta24 And please signoff the commit to fix the DCO ci issue.

**Comment by fisherxu** [comment]
Please squash the commits to 1

**Comment by rajatgupta24** [comment]
Hey @fisherxu, to prevent this test from failing (DCO), I just have to add ``-s`` in my ``commit`` command should I also add this in the documentation.

**Comment by fisherxu** [comment]
> Hey @fisherxu, to prevent this test from failing (DCO), I just have to add `-s` in my `commit` command should I also add this in the documentation.

If you can add it to docs, that's great :)

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
