### PR TITLE
Rewrite of site to support internationalisation. Changed the website theme.

### PR DESCRIPTION
**Pull request by anvithks**
This is a major re write of the documentation website. The following is the list of changes and improvements that have been made:  

- [x] Changed the website theme to [Academic theme](https://github.com/gcushen/hugo-academic) 

- [x] Multi-language support. Currently supports English (en) and Chinese (zh)

- [x] Mobile responsive

- [x] Documentation sitemap and structure updated.

- [ ] Chinese translation of documentation

### CODE REVIEW

**Comment by m1093782566** [comment]
Is there any way to preview the change?

**Comment by anvithks** [comment]
> Is there any way to preview the changes?

Yes. 
You can preview the site by clicking on the **Details** link in the deploy/netlify check above.

**Comment by prostil** [comment]
This is a big PR, it took me quite a while to go through, but everything looks good to me 
@m1093782566 you can merge the PR

**Comment by m1093782566** [comment]
@anvithks @prostil 

I can merge this PR now but we need to refine the document in follow-ups especially some of the contents are copied from Kubernetes which are incorrect for kubeedge.

**Comment by anvithks** [comment]
> @anvithks @prostil
> 
> I can merge this PR now but we need to refine the document in follow-ups especially some of the contents are copied from Kubernetes which are incorrect for kubeedge.

Correct @m1093782566 . I am now looking at all the files and will correct any incorrect content and  I will start adding missing content.

**Comment by m1093782566** [comment]
Great! Thanks @anvithks

**Pull request merged**
