### PR TITLE
Replacing Twitter with X

### LINKED ISSUE #390: Changing the Twitter logo from bird to X
**Describe the bug**
The logo of twitter has been changed from the iconic bird logo to X.
**To Reproduce**
1. Go to 'https://kubeedge.io/'
2. See error

**Screenshots**
Screenshot 2023-08-06 at 6 21 18 PM

### LINKED ISSUE #444: Change twitter icon to X icon
Change twitter icon to X icon.

### PR DESCRIPTION
**Pull request by 1Shubham7**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
docs update

* **What is the current behavior?** (You can also link to an open issue here)
We have a Twitter logo.

solves a part of #533

* **What is the new behavior (if this is a feature change)?**
I have replaced the twitter logo with X

Closes #444 
Closes #390 

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
no

* **Other information**:

### CODE REVIEW

**Comment by 1Shubham7** [comment]
@fisherxu @wbc6080, should we also replace Twitter as text with X in various parts of the docs? [example](https://github.com/kubeedge/website/blob/138f88cb4f59e3088689eb7073b721c7c825f825/docs/welcome/getting-started.md?plain=1#L49)

**Review by wbc6080 — COMMENTED** [review]
Good job!
/lgtm

**Review by Shelley-BaoYue — COMMENTED** [review]
Thanks for your contributions!  
/lgtm

**Pull request merged**
