### PR TITLE
PR template update

### PR DESCRIPTION
**Pull request by iArchitSharma**
* **Please check if the PR fulfills these requirements**
This PR fixes issue #583 

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Review by wbc6080 — COMMENTED** [review]
Thanks for your contribution. But there seems to be a problem with the line wrapping of the file:
Pr fix
In addition, I think it is better to keep the` PR fixes issue` field consistent with the kubeedge main repo. You can refer to the description of the main repo https://github.com/kubeedge/kubeedge/blob/master/.github/PULL_REQUEST_TEMPLATE.md.
main repo

**Comment by iArchitSharma** [comment]
@wbc6080 thanks, I've updated the template with the description of the main repo.

**Comment by iArchitSharma** [comment]
@wbc6080 by the way I forgot to sign my last commit, I hope the **DCO check** can be bypassed for this one.

**Review by fujitatomoya — APPROVED** [review]
lgtm

**Review by wbc6080 — COMMENTED** [review]
Sorry, every commit needs to be signed. But don’t worry, you can follow this guide https://github.com/kubeedge/website/pull/586/checks?check_run_id=26610418304 to add your signature @iArchitSharma 
sign

**Comment by iArchitSharma** [comment]
thanks @wbc6080 , re-signed my commit

**Review by Shelley-BaoYue — COMMENTED** [review]
/lgtm

**Review by fisherxu — COMMENTED** [review]
/approve

**Pull request merged**
