### PR TITLE
keadm reset does not have `--kube-config` flag anymore.

### PR DESCRIPTION
**Pull request by fujitatomoya**
* **Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Which issue(s) this PR fixes**:

N.A

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

- `keadm reset --kube-config=$HOME/.kube/config` does not work as shown in the documentation.

* **What is the current behavior?** (You can also link to an open issue here)

```bash
root@tomoyafujita:~# keadm reset --kube-config=$HOME/.kube/config
Error: unknown flag: --kube-config
Usage:
  keadm reset [flags]

Examples:

For cloud node:
keadm reset

For edge node:
keadm reset


Flags:
      --cloudcore-ipport string          Use this key to set kube-config path, eg: $HOME/.kube/config (default "/root/.kube/config")
      --force                            Reset the node without prompting for confirmation
  -h, --help                             help for reset
      --remote-runtime-endpoint string   Use this key to set container runtime endpoint

execute keadm command failed:  unknown flag: --kube-config
```

* **What is the new behavior (if this is a feature change)?**

- should be `keadm reset`.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No

* **Other information**:

N.A

### CODE REVIEW

**Review by fujitatomoya — COMMENTED** [review]
minor doc update, `keadm command failed:  unknown flag: --kube-config`.

**Review by wbc6080 — COMMENTED** [review]
Which version of keadm are you using? I have tried versions 1.15 and 1.18 of keadm, and both can recognize this parameter normally.
image

**Comment by fujitatomoya** [comment]
```bash
root@tomoyafujita:~# keadm version
version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"4f1da43e6807c127e549e5d4859ed1b66c6f5806", GitTreeState:"clean", BuildDate:"2024-07-12T03:02:51Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}
root@tomoyafujita:~# keadm reset --kube-config=$HOME/.kube/config
Error: unknown flag: --kube-config
Usage:
  keadm reset [flags]

Examples:

For cloud node:
keadm reset

For edge node:
keadm reset


Flags:
      --cloudcore-ipport string          Use this key to set kube-config path, eg: $HOME/.kube/config (default "/root/.kube/config")
      --force                            Reset the node without prompting for confirmation
  -h, --help                             help for reset
      --remote-runtime-endpoint string   Use this key to set container runtime endpoint

execute keadm command failed:  unknown flag: --kube-config
```

**Comment by wbc6080** [comment]
@fujitatomoya Yes, I have reproduced this result in my environment. This should be a bug in version 1.16. I will try to locate and fix it later.

**Comment by fujitatomoya** [comment]
@wbc6080 thanks for checking. if that is the backport miss or bug in specific version, please feel free to close this PR.

**Comment by fujitatomoya** [comment]
https://github.com/kubeedge/kubeedge/pull/5906 is the right way to take and replaces this one, i will go ahead to close this.

CCL @wbc6080

**Review by wbc6080 — COMMENTED** [review]
Still thanks to find this bug. :)

**Pull request closed without merging**
