### PR TITLE
Change twitter icon to X icon

### PR DESCRIPTION
**Pull request by pabitra0011**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

solved #444 

 Change twitter old icon to new X icon.

### CODE REVIEW

**Comment by Shelley-BaoYue** [comment]
Could you please adjust the size of the twitter logo to the same with the surrounding logos?

image

**Review by fisherxu — COMMENTED** [review]
@pabitra0011 Please download the logo from https://about.twitter.com/en/who-we-are/brand-toolkit, and it's better a black one :) And adjust the size as @Shelley-BaoYue said above

**Comment by fisherxu** [comment]
@pabitra0011 Looks great! And not sure why the icon looks not that clear..

**Comment by Shelley-BaoYue** [comment]
Hi, @pabitra0011,  Is this task still in progress? Please address the DCO error and it seems that some unrelated files, such as package-lock.json, have been mistakenly included in the PR.

**Comment by Shelley-BaoYue** [comment]
https://github.com/kubeedge/website/pull/543 has completed it  
/close

**Pull request closed without merging**
