### PR TITLE
fix:heading 3

### PR DESCRIPTION
**Pull request by nilisha-jais**
* **Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix

* **What is the current behavior?** (You can also link to an open issue here)

Screenshot (29)

* **What is the new behavior (if this is a feature change)?**

Screenshot (30)

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No

* **Other information**:

NA

### CODE REVIEW

**Comment by kevin-wangzefeng** [comment]
DCO check failed, please fix in commit message

**Comment by nilisha-jais** [comment]
> DCO check failed, please fix in commit message

Fixed that!

**Pull request merged**
