### PR TITLE
add support info of zhiyuan research institute

### PR DESCRIPTION
**Pull request by spring-fisher**
* **Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Which issue(s) this PR fixes**:

Fixes #

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

add support info of zhiyuan research institute

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Review by fisherxu — COMMENTED** [review]
Thanks for supporting KubeEdge! 
And it's better to use `zhiyuan-research-institute.svg` for the file name, and plz fix the DCO test, ref: https://github.com/kubeedge/website/pull/632/checks?check_run_id=29284337389

**Review by wbc6080 — COMMENTED** [review]
For more information about DCO, please refer to https://kubeedge.io/docs/developer/Supplemental_developer_guide

**Review by wbc6080 — COMMENTED** [review]
Thanks for adding support info. I have resubmitted the relevant PR according to the content you submitted https://github.com/kubeedge/website/pull/633. You can review whether there are any problems. :)

**Pull request closed without merging**
