### PR TITLE
re-design documentation directory

### PR DESCRIPTION
**Pull request by Shelley-BaoYue**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

docs update

* **What is the current behavior?** (You can also link to an open issue here)

re-design KubeEdge doc directory, enable community users and developers to learn more quickly and clearly.

### CODE REVIEW

**Review by kevin-wangzefeng — COMMENTED** [review]
Looks fine to me.
It would be great if we could describe the overall document structure design somewhere like "how to contribute document".

**Comment by Shelley-BaoYue** [comment]
> Looks fine to me. It would be great if we could describe the overall document structure design somewhere like "how to contribute document".

There is already some description about the document structure in doc `getting-started`, but it's not prominent and clear enough.  I will take a look and see how to optimize it.

**Comment by kevin-wangzefeng** [comment]
Sure, let's track it in another issue.

**Pull request merged**
