### PR TITLE
add job center

### PR DESCRIPTION
**Pull request by Shelley-BaoYue**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

feature

* **What is the new behavior (if this is a feature change)?**

add job center,  provide a platform for community partners and developers to exchange job opportunities.

* **Other information**:

there are still some things todo:
- [x] Hide the job center page until a job needs to be displayed. Currently, for the convenience of reviewing the effect, the page will be displayed in Chinese language. It will be modified after the code review.
- remove the demo after reviewing.
- [x] change the header image
- [x] The link(POST A JOB) will be modified after the code review is completed.

### CODE REVIEW

**Comment by kevin-wangzefeng** [comment]
Generally looks fine to me.
As for the "Post a Job", I'd suggest link to an instruction doc that explains how to create a PR to add a Job Posting. And also requirements may be included in the instructions.

**Comment by Shelley-BaoYue** [comment]
> Generally looks fine to me. As for the "Post a Job", I'd suggest link to an instruction doc that explains how to create a PR to add a Job Posting. And also requirements may be included in the instructions.

Done. "POST A JOB" will link to [README](https://github.com/kubeedge/website/pull/404/files#diff-1336001f93e3388fa7e6525412534f3ad1228f1d0d40e8c6f9a9335c80fbc918) after pr merged.

**Review by kevin-wangzefeng — COMMENTED** [review]
/approve

**Pull request merged**
