### PR TITLE
An article on source code analysis of kubeedge's overall architecture

### PR DESCRIPTION
**Pull request by WormOn**
* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** ( docs )

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by kevin-wangzefeng** [comment]
@WormOn Please `mv source-code-analysis/kubeedge-architecture.md source-code-analysis/index.md`

**Comment by WormOn** [comment]
> @WormOn Please `mv source-code-analysis/kubeedge-architecture.md source-code-analysis/index.md`

OK.

**Comment by kevin-wangzefeng** [comment]
/approve cancel
The PR is now empty, @WormOn can you fix it?

**Comment by WormOn** [comment]
> /approve cancel
> The PR is now empty, @WormOn can you fix it?

Fixed!

**Pull request closed without merging**
