### PR TITLE
Add device crd, mapper, mapper-framework docs

### PR DESCRIPTION
**Pull request by wbc6080**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
update dmi and mapper-framework docs, introduce v1beta1 device API

### CODE REVIEW

**Comment by wbc6080** [comment]
cc @Shelley-BaoYue @fisherxu thanks

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
