### PR TITLE
Accessibility add links name to icons

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/kubeedge/website/issues/437

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
@kevin-wangzefeng
Corrected using the example of the main site https://docusaurus.io/

**Comment by Arhell** [comment]
Please take a look, it's been a while since you merged with the main branch.

**Review by Shelley-BaoYue — COMMENTED** [review]
I'm not very familiar with frontend, I would like to learn what effect if we add this aria-label?

**Comment by Arhell** [comment]
> aria-label

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label

**Pull request closed without merging**
