### PR TITLE
add use case for china's highways and cnooc

### PR DESCRIPTION
**Pull request by fisherxu**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Review by kevin-wangzefeng — COMMENTED** [review]
/approve

**Review by fisherxu — COMMENTED** [review]
The content is mainly copied from #323 #324 by @faweizhao26, so add fawei as co-author in the commit, PTAL @benjaminhuo @faweizhao26 Thanks.

**Comment by benjaminhuo** [comment]
> The content is mainly copied from #323 #324 by @faweizhao26, so add fawei as co-author in the commit, PTAL @benjaminhuo @faweizhao26 Thanks.

Thanks!

/lgtm
/approve

**Pull request merged**
