### PR TITLE
Fix how to enable Stream in advanced debug section.

### PR DESCRIPTION
**Pull request by fujitatomoya**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Minor cosmetic doc update for https://kubeedge.io/docs/advanced/debug/

* **What is the current behavior?** (You can also link to an open issue here)

https://kubeedge.io/docs/advanced/debug/

* **What is the new behavior (if this is a feature change)?**

add more concrete command how to change for both `cloudcore` and `edgecore`, depends on the install mode.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No

* **Other information**:

part of https://github.com/kubeedge/kubeedge/issues/5355

### CODE REVIEW

**Review by fujitatomoya — COMMENTED** [review]
similar change could be applied to else where, but i just focused on this specific procedure with this PR.

**Comment by fujitatomoya** [comment]
@fisherxu minor doc update, i could use review.

**Comment by fujitatomoya** [comment]
@kevin-wangzefeng @edisonxiang minor patch, could you take a look?

**Review by fisherxu — COMMENTED** [review]
@fujitatomoya Thanks for the fixing, and sorry for the delay due to the vacation :) 
/lgtm
/approve

**Pull request merged**
