### PR TITLE
fix:wrong path about how to configure kubectl logs function

### PR DESCRIPTION
**Pull request by QeelinDarly**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
docs update

* **What is the current behavior?** (You can also link to an open issue here)
The document "turn on kubectl logs" is located in the "keadm initialization" document, but not in "Enable Kubectl logs/exec to debug pods on the edge" . I just create document in Chinese in here.

* **What is the new behavior (if this is a feature change)?**
Delete “启用 kubectl logs 功能” in "使用Keadm进行部署", move it to "高级配置>通过开启kubectl logs来debug边缘节点的pod".

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
Nothing.

* **Other information**:

### CODE REVIEW

**Comment by QeelinDarly** [comment]
/assign @dingyin
I don't know which part I lost, please help me to check it.

**Comment by kevin-wangzefeng** [comment]
Unfortunately the Chinese version content is not up to date with English one, we would need to fix it first

**Comment by QeelinDarly** [comment]
> Unfortunately the Chinese version content is not up to date with English one, we would need to fix it first

I'm glad you help me to do the code review. I have fixed English document and it is synchronized with Chinese now.

**Pull request closed without merging**
