### PR TITLE
Fixed some doc errors.

### PR DESCRIPTION
**Pull request by suojy**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Review by anvithks — CHANGES_REQUESTED** [review]
Overall LGTM. 
Please rebase and resolve the merge conflicts.

**Comment by kevin-wangzefeng** [comment]
@suojy Thanks for your PR, to rebase onto master, you can:
```bash
git add remote upstream https://github.com/kubeedge/website.git
git remote update upstream
git checkout <your working branch>
git rebase upstream/master
```

**Review by anvithks — APPROVED** [review]
LGTM

**Comment by suojy** [comment]
> @suojy Thanks for your PR, to rebase onto master, you can:
> 
> ```shell
> git add remote upstream https://github.com/kubeedge/website.git
> git remote update upstream
> git checkout <your working branch>
> git rebase upstream/master
> ```
> 
> Please note that you would need to use force push after rebase:
> 
> ```shell
> git push -f origin <your working branch>
> ```
> 
> origin is the git address of your fork repo: https://github.com/suojy/website.git

Thank you so much for your help.

**Review by anvithks — APPROVED** [review]
/lgtm

**Pull request merged**
