### PR TITLE
fix toggle menu on close

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/kubeedge/website/issues/209

### CODE REVIEW

**Comment by Arhell** [comment]
/assign @kevin-wangzefeng
no "jumping" on close

**Comment by fisherxu** [comment]
Could you please add more description? What does this pr fixed? Thanks! @Arhell

**Comment by Arhell** [comment]
> Could you please add more description? What does this pr fixed? Thanks! @Arhell

As shown in the picture here https://github.com/kubeedge/website/issues/209

When closing the menu, the content jumps a little, this PR fixes it

**Comment by fisherxu** [comment]
> > Could you please add more description? What does this pr fixed? Thanks! @Arhell
> 
> As shown in the picture here #209
> 
> When closing the menu, the content jumps a little, this PR fixes it

Looks good.
/lgtm
/approve

**Pull request merged**
