### PR TITLE
Update links in supporters section

### LINKED ISSUE #374: Incorrect and missing Links in supporters section
**Describe the bug**
 - In the supporters section of home page, the link for EMQ is incorrect and Orange does not have a link redirecting to its website.

### PR DESCRIPTION
**Pull request by VSatwika**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
 - fixes #374 
 - Fixed incorrect link for EMQ
 - Added link for Orange

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please sign DCO
https://github.com/kubeedge/website/pull/375/checks?check_run_id=15548944053

**Comment by VSatwika** [comment]
@Arhell Sir, I have opened a new PR (#379) which is signed.
Please let me know if it alright.

**Comment by Shelley-BaoYue** [comment]
please fix the `DCO` failed as follows:
image

**Comment by VSatwika** [comment]
@Shelley-BaoYue I've done the suggested changes.

**Comment by Shelley-BaoYue** [comment]
@VSatwika Thanks for your contributions! 
/lgtm

**Comment by VSatwika** [comment]
@Shelley-BaoYue Thank you so much for helping me out😄

**Pull request merged**
