### PR TITLE
Automated cherry pick of #623: update versions for 1.18

### PR DESCRIPTION
**Pull request by fisherxu**
Cherry pick of #623 on release-1.18.

#623: update versions for 1.18

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Review by Shelley-BaoYue — COMMENTED** [review]
/lgtm

**Review by Shelley-BaoYue — COMMENTED** [review]
cc @zhiyingfang2022 @WillardHu @wbc6080

**Comment by WillardHu** [comment]
lgtm

**Review by wbc6080 — COMMENTED** [review]
/lgtm

**Review by Shelley-BaoYue — COMMENTED** [review]
/approve

**Pull request merged**
